### ISSUE TITLE
Human dorsolateral prefrontal cortex data

### ISSUE THREAD

**Issue by WUZHExl** [feiyoung/DR.SC#1]
Hello, can you provide the data for analysis in visium_human_dorsolateral_prefrontal_Cortex.r?
I can get the raw data, but I'm not sure what goes from the raw data to the data for your analysis.

**Comment by feiyoung** [comment]
Thank you for your attention to DR-SC. We preprocessed the raw data as follows. First, we used SPARK (https://github.com/xzhoulab/SPARK/) to choose the top 2000 spatially variable genes. Then, Log-normalization was performed on the selected gene-spot matrix, which was implemented by using the R function NormalizeData in the Seurat package. Finally, we input the normlized matrix as well as spatial coordinates into DR.SC core function. 

In DR.SC package, we provide a high-level function to implement DR-SC, named DR.SC. User only require to create a proper Seurat object to input it to the DR.SC function. You can refer to the vignettes for more details: https://feiyoung.github.io/DR.SC/articles/DR.SC.DLPFC.html

**Comment by WUZHExl** [comment]
Thank you for your help,&nbsp;Professor Liu.




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "feiyoung/DR.SC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月31日(星期天) 晚上10:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [feiyoung/DR.SC] Human dorsolateral prefrontal cortex data (Issue #1)





 
Thank you for your attention to DR-SC. We preprocessed the raw data as follows. First, we used SPARK (https://github.com/xzhoulab/SPARK/) to choose the top 2000 spatially variable genes. Then, Log-normalization was performed on the selected gene-spot matrix, which was implemented by using the R function NormalizeData in the Seurat package. Finally, we input the normlized matrix as well as spatial coordinates into DR.SC core function.
 
In DR.SC package, we provide a high-level function to implement DR-SC, named DR.SC. User only require to create a proper Seurat object to input it to the DR.SC function. You can refer to the vignettes for more details: https://feiyoung.github.io/DR.SC/articles/DR.SC.HCC1.html

**Comment by feiyoung** [comment]
You are wellcome. In addition, the DLPFC data used in our paper are uploaded; Please see https://github.com/feiyoung/DR-SC.Analysis/tree/main/data/DLPFC_data.

**Comment by WUZHExl** [comment]
Hello, when I run visium_human_dorsolateral_prefrontal_cortex.R, in
`ij <-find_neighbors(sce, platform="Visium")`has an error. 
`Error in rownames<-(*tmp*, value = value[[2]]) : 
  invalid rownames length`
What is the cause?

**Comment by feiyoung** [comment]
> Hello, when I run visium_human_dorsolateral_prefrontal_cortex.R, in `ij <-find_neighbors(sce, platform="Visium")`has an error. `Error in rownames<-(*tmp*, value = value[[2]]) : invalid rownames length` What is the cause?

find_neighbors function has been updated that only support matrix object rather than complex singleCellExperiment object input. You can change: ij <- find_neighbors(sce, platform="Visium")
to : ij <- find_neighbors(pos, platform="Visium").
Hope this can help you!

**Comment by WUZHExl** [comment]
Thank you very much for sharing the data with me.It help me a lot.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "feiyoung/DR.SC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月31日(星期天) 晚上10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [feiyoung/DR.SC] Human dorsolateral prefrontal cortex data (Issue #1)





 
You are wellcome. In addition, the DLPFC data used in our paper are uploaded; Please see https://github.com/feiyoung/DR-SC.Analysis/tree/main/data/DLPFC_data.
